### ISSUE TITLE
Rotating device

### ISSUE THREAD

**Issue by seth-peterson** [jacklam718/react-native-popup-dialog#12]
Starting the app in one orientation, then later changing to a different orientation doesn't change the popup dialog. For example, starting in landscape then rotating to portrait, then opening the popup. The pop up will be off centered as if it is still landscape.  

I can only say for sure this happens on iOS emulator, I have not tested on device or android.

**Comment by samothx** [comment]
I have seen it in the android emulator and on a real android device too.

**Comment by dorthwein** [comment]
+1

**Comment by jacklam718** [comment]
@seth-peterson, @samothx 
@dorthwein Has been solved this issue and I've been merged he's PR and released a new version.
Please install the version 0.4.16

If any issues, please let me know, thanks.

**Comment by nurbek-ab** [comment]
It seems to me the issue is still there. At least I can reproduce it on android emulator, Windows 7.
I opened the dialog in landscape mode and changed it to portrait. The gray overlay is cut from the bottom and the dialog has a significant offset to the right.
![screenshot_1496754991](https://cloud.githubusercontent.com/assets/3624386/26831192/af56f0b2-4af5-11e7-83d0-c319ed1fda93.png)

**Comment by poojanshah2005** [comment]
+1
